server:
  port: 8081
  context-path: /quartz
  session-timeout: 60
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
### mybatis配置
mybatis:
  # Mapper路径
  mapper-locations: classpath*:mapper/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qz?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 初始化时建立物理连接个数
    initialSize: 5
    # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 50
    # 获取连接最大等待时间
    maxWait: 60000
#  devtools:
#    livereload:
#      enabled: true
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
    cache-period: 0
    mode: LEGACYHTML5
    template:
      cache: false
